### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### Ameobea/TickGrinder now has a Chat Room on Gitter

@Ameobea has just created a chat room. You can visit it here: [https://gitter.im/TickGrinder/Lobby](https://gitter.im/TickGrinder/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/TickGrinder/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by djKooks** [comment]
Oh, is project has been renamed?

**Comment by Ameobea** [comment]
Indeed!  I've gone for the name TickGrinder.  I'm working on a website and stuff as well.

I'm torn between waiting until this is presentable and user-friendly and trying to make an impression or releasing early to try to get some interest built up in its development!

**Comment by djKooks** [comment]
@Ameobea Okay~is it still not allow to build and run test yet?

**Comment by Ameobea** [comment]
You should be able to build it just fine!  It's Linux-only however due to a lot of specialized dependencies.  

If you have a Linux machine (or VPS), just `git pull` and then `make` and it should get you into the configurator!

**Pull request merged**
